apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyber-threat-dashboard
  labels:
    app: cyber-threat-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyber-threat-dashboard
  template:
    metadata:
      labels:
        app: cyber-threat-dashboard
    spec:
      containers:
      - name: cyber-threat-dashboard
        image: jiaahmed/cyber-threat-dashboard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
