apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cyber-threat-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyber-threat-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyber-threat-dashboard
  template:
    metadata:
      labels:
        app: cyber-threat-dashboard
    spec:
      containers:
      - name: cyber-threat-dashboard
        image: jiaahmed/cyber-threat-dashboard:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: cyber-threat-pvc
