apiVersion: v1
kind: Service
metadata:
  name: cyber-threat-service
  labels:
    app: cyber-threat-dashboard
spec:
  selector:
    app: cyber-threat-dashboard
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31701
  type: NodePort
